ELASTICSEARCH_RESULT_RESPONSE = {
'_shards': {'failed': 0, 'successful': 3, 'total': 3},
'hits': {'hits': [{'_id': '5817809',
    '_index': 'github_users',
    '_score': None,
    '_source': {'contributions': 991,
     'location': 'Barcelona Spain',
     'repositories': 29,
     'user_id': 5817809,
     'user_profile_page': 'https://github.com/antonk52',
     'username': 'Anton'},
    '_type': 'user',
    'sort': [991, 29]},
   {'_id': '179462',
    '_index': 'github_users',
    '_score': None,
    '_source': {'contributions': 980,
     'location': 'Barcelona',
     'repositories': 76,
     'user_id': 179462,
     'user_profile_page': 'https://github.com/carlosvillu',
     'username': 'Carlos Villuendas Zambrana'},
    '_type': 'user',
    'sort': [980, 76]},
   {'_id': '11041768',
    '_index': 'github_users',
    '_score': None,
    '_source': {'contributions': 977,
     'location': 'Barcelona, Spain',
     'repositories': 26,
     'user_id': 11041768,
     'user_profile_page': 'https://github.com/oscmansan',
     'username': 'Oscar Mañas'},
    '_type': 'user',
    'sort': [977, 26]},
   {'_id': '6461230',
    '_index': 'github_users',
    '_score': None,
    '_source': {'contributions': 975,
     'location': 'Barcelona',
     'repositories': 10,
     'user_id': 6461230,
     'user_profile_page': 'https://github.com/Westermann',
     'username': 'Westermann'},
    '_type': 'user',
    'sort': [975, 10]},
   {'_id': '1517153',
    '_index': 'github_users',
    '_score': None,
    '_source': {'contributions': 970,
     'location': 'Barcelona',
     'repositories': 160,
     'user_id': 1517153,
     'user_profile_page': 'https://github.com/lordofthejars',
     'username': 'Alex Soto'},
    '_type': 'user',
    'sort': [970, 160]}],
  'max_score': None,
  'total': 1021},
 'timed_out': False,
 'took': 1
}